In [10]:
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer


In [109]:
import numpy as np

In [63]:
from nltk.stem.porter import PorterStemmer
from nlp_cl_start import tokenize

In [30]:
import pickle

In [4]:
km = KMeans()

In [7]:
km.n_clusters =16
km.n_clusters

16

In [8]:
import numpy as np

In [ ]:
km.fit()

In [11]:
x = np.random.random_integers(0,100, 1000)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  """Entry point for launching an IPython kernel.


In [13]:
km.fit(x.reshape(-1, 1))

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=16, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [14]:
km.cluster_centers_

array([[22.85185185],
       [83.80769231],
       [46.49180328],
       [59.25806452],
       [ 9.75362319],
       [91.01315789],
       [65.79365079],
       [34.71794872],
       [71.42592593],
       [15.95180723],
       [ 2.87692308],
       [53.27272727],
       [77.52941176],
       [97.63461538],
       [40.5       ],
       [29.86538462]])

In [19]:
c =np.linspace(0,100,16)

In [20]:
km.cluster_centers_ = c

In [21]:
km.cluster_centers_

array([  0.        ,   6.66666667,  13.33333333,  20.        ,
        26.66666667,  33.33333333,  40.        ,  46.66666667,
        53.33333333,  60.        ,  66.66666667,  73.33333333,
        80.        ,  86.66666667,  93.33333333, 100.        ])

In [11]:
cv = CountVectorizer()
idf = TfidfTransformer()

In [16]:
cv.fit(['aaaa  dd', 'dddd gggg', 'sss dddd'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [20]:
cv.vocabulary_ = {'food' :0,
 'order':1,
 'place':2,
 'time':3,
 'like':4,
 'servic':5,
 'good':6,
 'go':7,
 'get':8,
 'one':9,
 'us':10,
 'would':11,
 'back':12,
 'ask':13,
 'restaur':14,
 'wait':15}

In [22]:
cv.vocabulary_

{'food': 0,
 'order': 1,
 'place': 2,
 'time': 3,
 'like': 4,
 'servic': 5,
 'good': 6,
 'go': 7,
 'get': 8,
 'one': 9,
 'us': 10,
 'would': 11,
 'back': 12,
 'ask': 13,
 'restaur': 14,
 'wait': 15}

In [56]:
rx = ["The lunch and dinner menus are a bit different, with the lunch menu featuring more sandwiches and things, so maybe the comment I just made about people not coming for a burger is wrong. Either way, this restaurant is pretty fancy and features quite a"]

In [28]:
x.get_shape()

(1, 16)

In [ ]:
with open('model_parts/centers', 'rb') as f:
    new_centers = pickle.load(f)
with open('model_parts/vocab', 'rb') as f:
    new_vocab = pickle.load(f)

In [33]:
with open('model_parts/idf', 'rb') as f:
    new_idf =pickle.load( f)

In [44]:
new_vocab_dict = {}

['food',
 'order',
 'place',
 'time',
 'like',
 'servic',
 'good',
 'go',
 'get',
 'one',
 'us',
 'would',
 'back',
 'ask',
 'restaur',
 'wait',
 'even',
 'tabl',
 'came',
 'got',
 'minut',
 'come',
 'tri',
 'want',
 'realli',
 'never',
 'tast',
 'eat',
 'look',
 'chicken',
 'drink',
 'said',
 'server',
 'went',
 'could',
 'bad',
 'better',
 'say',
 'manag',
 'make',
 'first',
 'take',
 'great',
 'menu',
 'peopl',
 'price',
 'custom',
 'pizza',
 'know',
 'give',
 'also',
 'fri',
 'disappoint',
 'told',
 'much',
 'two',
 'experi',
 'took',
 'meal',
 'way',
 'thing',
 'well',
 'sauc',
 'anoth',
 'waitress',
 'star',
 'serv',
 'bar',
 'think',
 'review',
 'salad',
 'busi',
 'locat',
 'ever',
 'hour',
 'nice',
 'seem',
 'friend',
 'still',
 'walk',
 'burger',
 'call',
 'staff',
 'seat',
 'chees',
 'made',
 'dish',
 'cook',
 'night',
 'pretti',
 'noth',
 'need',
 'use',
 'last',
 'ok',
 'around',
 'check',
 'left',
 'day',
 'right',
 'long',
 'see',
 'meat',
 'dinner',
 'someth',
 'littl',


In [53]:
len(new_vocab)

5000

In [52]:
s = {key: value for (key, value) in zip(l,range(3))}
s

{'a': 0, 'b': 1, 'c': 2}

In [54]:
new_vocab_dict = {key: value for (key, value) in zip(new_vocab,range(5000))}

In [64]:
cv2 = CountVectorizer( tokenizer= tokenize, vocabulary= new_vocab_dict )

In [69]:
idf2 = TfidfTransformer()

In [114]:
idf2.idf_ = new_idf

AttributeError: can't set attribute

In [115]:
new_idf

array([0.60330892, 0.84252972, 0.89160188, ..., 7.57342848, 7.62472178,
       7.76580038])

In [82]:
km2 = KMeans(n_clusters = 18)

In [93]:
XX = cv2.transform(rx *18)

In [94]:
km2.fit(XX)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=18, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [112]:
km2.cluster_centers_ = new_clusters

In [110]:
new_clusters = np.array(new_centers)

In [111]:
type(new_clusters)

numpy.ndarray

In [101]:
XX

<18x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 378 stored elements in Compressed Sparse Row format>

In [142]:
x.count_nonzero()

21

In [113]:
km2.predict(x)

array([1], dtype=int32)

In [116]:
idf2.fit(XX)

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

In [120]:
idf2.idf_ 

array([3.94443898, 3.94443898, 3.94443898, ..., 3.94443898, 3.94443898,
       3.94443898])

In [132]:
y =idf2.transform(x)

In [140]:
new_idf

array([0.60330892, 0.84252972, 0.89160188, ..., 7.57342848, 7.62472178,
       7.76580038])

In [150]:
len(new_idf)

5000

In [155]:
zz = x.toarray()[0]*new_idf

In [165]:
np.arange(0,5000)[zz!=0]

array([  14,   21,   43,   44,   59,   60,   80,   85,   89,  103,  113,
        119,  134,  177,  182,  183,  241,  256,  744, 1300, 1842])

In [166]:
zz[zz!=0]

array([ 1.50396177,  1.58009069,  4.12929524,  1.97121741,  2.0138051 ,
        2.0605039 ,  2.78739614,  2.23253067,  2.3115158 ,  2.47524029,
        2.8910658 ,  5.27216197,  2.5848684 ,  2.78219375,  2.81168199,
        2.79220635,  2.97982493,  3.10551089,  4.28876492,  5.16423365,
       11.4578369 ])

Pipeline: 
CountVectorizer, multiply by idf, KMeans

In [167]:
with open('r_first.txt') as f:
    r1 = f.read()

In [177]:
r1_cv = cv2.transform([r1, r1])

In [178]:
r1_idf = r1_cv.toarray()[0] *new_idf

In [181]:
x = r1_cv.toarray() *new_idf

(2, 5000)

In [179]:
{key:value for (key, value) in zip(np.arange(0,5000)[r1_idf!=0],r1_idf[r1_idf!=0])}

{0: 0.6033089193626404,
 1: 0.8425297209220866,
 3: 1.1017779477994667,
 4: 2.1827840813892454,
 6: 3.2769326307004665,
 7: 2.1433769259456716,
 8: 3.516275656520924,
 9: 1.222455509598619,
 11: 2.5850355897301447,
 12: 2.4453473288915886,
 13: 1.527416566294614,
 14: 3.0079235395776127,
 17: 1.7455128069040162,
 18: 1.5925194493728618,
 21: 4.740272073154995,
 24: 1.6629028779386974,
 34: 5.543898176679713,
 37: 1.890869644336753,
 40: 3.734132011243478,
 42: 9.55320814294323,
 43: 8.258590471345821,
 44: 7.884869659975887,
 45: 3.9492724434855146,
 48: 1.9755622334766756,
 50: 1.9675345087042515,
 51: 6.64805123005676,
 59: 6.041415310754196,
 60: 2.0605038957013675,
 61: 4.177263098101345,
 63: 2.13513180593985,
 67: 4.825014218868506,
 68: 4.266138332232245,
 72: 4.663098402193987,
 78: 4.423568532265932,
 80: 22.29916909996506,
 84: 5.000575966187348,
 85: 4.465061336916345,
 87: 7.091826989099719,
 89: 4.623031595774181,
 90: 2.253716619139134,
 92: 2.333932676801633,
 94: 7.0515

In [184]:
cl = km2.predict(x)

In [187]:
km2.predict(r1_idf.reshape(1,-1))

array([8], dtype=int32)

In [189]:
cv2.transform([r1]).toarray()*new_idf

array([[0.60330892, 0.84252972, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [193]:
with open('model_parts/cv.mdl','wb') as f:
    pickle.dump(cv2,f)
with open('model_parts/km.mdl','wb') as f:
    pickle.dump(km2,f)
